# These are supported funding model platforms

patreon: msxbas2rom
custom: ['https://www.paypal.com/donate?business=X793ZKW56SRBY&item_name=MSXBAS2ROM+compiler+project&currency_code=BRL', 'https://www.catarse.me/msxbas2rom_msx_basic_compiler_21ec', 'https://amaurycarvalho.itch.io/']
