/***
 * @file cdb_export_strategy.cpp
 * @brief CDB (*.cdb) dummy export strategy implementation
 * @author Amaury Carvalho (2019-2026)
 * @note
 */

#include "cdb_export_strategy.h"

bool CdbExportStrategy::save(SymbolManager* symbolManager, BuildOptions* opts) {
  FILE* file;
  (void)symbolManager;

  if ((file = fopen(opts->cdbFilename.c_str(), "w"))) {
    const char* content =
        "; Dummy CDB generated by msxbas2rom\n"
        "; TODO: implement SDCC CDB export format\n";
    fwrite(content, 1, strlen(content), file);
    fclose(file);
    return true;
  }
  return false;
}
