01 WIDTH 40 : ON INTERVAL=100 GOSUB 505 : INTERVAL ON 
02 ON STRIG GOSUB 507 : STRIG(0) ON
03 A = 0 : B = 0 : C = 0 
04 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
05 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
06 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
07 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
08 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
09 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
10 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
11 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
12 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
13 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
14 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
15 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
16 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
17 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
18 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
19 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
20 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
21 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
22 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
23 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
24 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
25 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
26 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
27 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
28 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
29 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
30 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
31 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
32 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
33 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
34 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
35 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
36 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
37 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
38 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
39 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
40 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
41 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
42 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
43 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
44 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
45 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
46 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
47 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
48 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
49 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
50 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
51 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
52 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
53 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
54 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
55 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
56 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
57 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
58 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
59 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
60 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
61 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
62 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
63 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
64 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
65 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
66 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
67 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
68 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
69 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
70 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
71 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
72 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
73 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
74 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
75 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
76 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
77 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
78 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
79 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
80 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
81 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
82 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
83 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
84 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
85 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
86 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
87 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
88 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
89 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
90 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
91 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
92 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
93 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
94 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
95 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
96 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
97 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
98 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
99 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
100 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
101 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
102 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
103 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
104 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
105 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
106 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
107 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
108 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
109 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
110 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
111 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
112 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
113 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
114 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
115 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
116 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
117 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
118 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
119 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
120 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
121 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
122 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
123 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
124 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
125 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
126 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
127 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
128 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
129 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
130 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
131 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
132 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
133 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
134 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
135 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
136 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
137 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
138 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
139 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
140 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
141 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
142 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
143 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
144 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
145 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
146 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
147 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
148 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
149 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
150 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
151 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
152 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
153 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
154 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
155 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
156 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
157 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
158 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
159 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
160 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
161 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
162 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
163 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
164 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
165 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
166 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
167 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
168 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
169 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
170 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
171 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
172 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
173 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
174 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
175 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
176 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
177 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
178 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
179 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
180 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
181 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
182 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
183 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
184 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
185 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
186 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
187 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
188 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
189 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
190 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
191 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
192 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
193 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
194 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
195 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
196 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
197 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
198 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
199 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
200 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
201 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
202 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
203 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
204 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
205 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
206 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
207 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
208 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
209 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
210 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
211 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
212 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
213 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
214 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
215 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
216 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
217 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
218 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
219 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
220 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
221 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
222 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
223 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
224 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
225 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
226 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
227 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
228 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
229 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
230 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
231 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
232 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
233 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
234 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
235 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
236 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
237 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
238 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
239 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
240 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
241 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
242 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
243 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
244 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
245 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
246 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
247 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
248 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
249 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
250 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
251 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
252 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
253 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
254 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
255 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
256 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
257 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
258 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
259 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
260 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
261 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
262 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
263 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
264 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
265 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
266 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
267 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
268 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
269 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
270 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
271 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
272 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
273 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
274 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
275 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
276 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
277 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
278 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
279 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
280 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
281 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
282 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
283 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
284 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
285 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
286 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
287 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
288 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
289 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
290 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
291 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
292 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
293 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
294 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
295 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
296 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
297 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
298 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
299 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
300 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
301 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
302 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
303 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
304 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
305 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
306 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
307 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
308 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
309 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
310 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
311 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
312 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
313 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
314 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
315 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
316 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
317 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
318 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
319 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
320 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
321 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
322 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
323 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
324 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
325 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
326 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
327 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
328 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
329 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
330 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
331 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
332 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
333 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
334 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
335 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
336 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
337 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
338 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
339 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
340 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
341 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
342 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
343 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
344 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
345 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
346 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
347 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
348 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
349 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
350 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
351 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
352 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
353 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
354 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
355 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
356 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
357 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
358 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
359 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
360 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
361 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
362 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
363 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
364 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
365 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
366 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
367 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
368 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
369 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
370 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
371 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
372 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
373 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
374 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
375 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
376 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
377 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
378 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
379 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
380 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
381 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
382 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
383 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
384 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
385 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
386 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
387 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
388 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
389 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
390 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
391 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
392 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
393 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
394 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
395 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
396 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
397 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
398 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
399 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2  
400 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
401 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
402 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
403 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
404 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
405 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
406 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
407 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
408 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
409 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
410 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
411 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
412 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
413 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
414 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
415 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
416 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
417 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
418 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
419 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
420 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
421 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
422 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
423 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
424 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
425 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
426 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
427 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
428 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
429 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
430 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
431 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
432 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
433 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
434 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
435 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
436 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
437 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
438 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
439 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
440 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
441 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
442 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
443 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
444 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
445 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
446 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
447 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
448 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
449 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
450 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
451 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
452 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
453 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
454 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
455 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
456 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
457 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
458 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
459 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
460 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
461 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
462 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
463 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
464 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
465 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
466 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
467 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
468 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
469 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
470 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
471 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
472 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
473 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
474 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
475 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
476 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
477 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
478 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
479 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
480 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
481 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
482 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
483 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
484 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
485 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
486 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
487 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
488 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
489 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
490 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
491 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
492 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
493 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
494 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
495 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
496 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
497 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
498 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
499 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
500 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
501 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
502 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
503 A = A + 1 : B = A * 2 + 1 : C = C + A / B : D = A + B + C : D = D * 2 
504 GOTO 3
505 PRINT A, B, C, D
506 RETURN
507 PRINT "SPACE PRESSED" 
508 RETURN 03


