01 WIDTH 40 : A = 0 : B = 0 : C = 0
02 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
03 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
04 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
05 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
06 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
07 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
08 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
09 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
10 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
11 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
12 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
13 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
14 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
15 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
16 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
17 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
18 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
19 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
20 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
21 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
22 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
23 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
24 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
25 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
26 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
27 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
28 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
29 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
30 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
31 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
32 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
33 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
34 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
35 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
36 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
37 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
38 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
39 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
40 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
41 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
42 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
43 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
44 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
45 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
46 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
47 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
48 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
49 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
50 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
51 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
52 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
53 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
54 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
55 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
56 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
57 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
58 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
59 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
60 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
61 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
62 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
63 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
64 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
65 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
66 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
67 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
68 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
69 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
70 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
71 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
72 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
73 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
74 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
75 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
76 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
77 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
78 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
79 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
80 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
81 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
82 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
83 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
84 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
85 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
86 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
87 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
88 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
89 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
90 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
91 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
92 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
93 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
94 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
95 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
96 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
97 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
98 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
99 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
100 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
101 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
102 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
103 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
104 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
105 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
106 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
107 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
108 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
109 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
110 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
111 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
112 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
113 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
114 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
115 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
116 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
117 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
118 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
119 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
120 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
121 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
122 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
123 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
124 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
125 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
126 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
127 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
128 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
129 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
130 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
131 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
132 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
133 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
134 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
135 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
136 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
137 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
138 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
139 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
140 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
141 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
142 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
143 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
144 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
145 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
146 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
147 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
148 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
149 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
150 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
151 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
152 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
153 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
154 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
155 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
156 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
157 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
158 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
159 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
160 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
161 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
162 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
163 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
164 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
165 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
166 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
167 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
168 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
169 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
170 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
171 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
172 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
173 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
174 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
175 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
176 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
177 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
178 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
179 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
180 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
181 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
182 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
183 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
184 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
185 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
186 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
187 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
188 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
189 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
190 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
191 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
192 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
193 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
194 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
195 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
196 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
197 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
198 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
199 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
200 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
201 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
202 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
203 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
204 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
205 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
206 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
207 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
208 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
209 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
210 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
211 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
212 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
213 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
214 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
215 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
216 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
217 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
218 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
219 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
220 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
221 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
222 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
223 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
224 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
225 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
226 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
227 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
228 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
229 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
230 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
231 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
232 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
233 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
234 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
235 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
236 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
237 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
238 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
239 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
240 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
241 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
242 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
243 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
244 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
245 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
246 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
247 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
248 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
249 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
250 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
251 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
252 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
253 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
254 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
255 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
256 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
257 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
258 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
259 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
260 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
261 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
262 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
263 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
264 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
265 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
266 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
267 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
268 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
269 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
270 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
271 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
272 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
273 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
274 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
275 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
276 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
277 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
278 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
279 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
280 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
281 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
282 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
283 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
284 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
285 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
286 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
287 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
288 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
289 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
290 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
291 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
292 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
293 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
294 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
295 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
296 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
297 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
298 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
299 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
300 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
301 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
302 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
303 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
304 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
305 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
306 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
307 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
308 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
309 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
310 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
311 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
312 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
313 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
314 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
315 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
316 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
317 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
318 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
319 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
320 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
321 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
322 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
323 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
324 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
325 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
326 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
327 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
328 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
329 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
330 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
331 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
332 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
333 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
334 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
335 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
336 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
337 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
338 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
339 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
340 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
341 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
342 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
343 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
344 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
345 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
346 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
347 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
348 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
349 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
350 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
351 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
352 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
353 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
354 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
355 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
356 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
357 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
358 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
359 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
360 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
361 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
362 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
363 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
364 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
365 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
366 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
367 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
368 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
369 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
370 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
371 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
372 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
373 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
374 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
375 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
376 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
377 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
378 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
379 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
380 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
381 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
382 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
383 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
384 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
385 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
386 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
387 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
388 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
389 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
390 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
391 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
392 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
393 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
394 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
395 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
396 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
397 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
398 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
399 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C 
400 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
401 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
402 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
403 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
404 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
405 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
406 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
407 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
408 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
409 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
410 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
411 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
412 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
413 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
414 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
415 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
416 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
417 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
418 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
419 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
420 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
421 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
422 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
423 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
424 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
425 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
426 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
427 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
428 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
429 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
430 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
431 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
432 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
433 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
434 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
435 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
436 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
437 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
438 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
439 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
440 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
441 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
442 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
443 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
444 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
445 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
446 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
447 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
448 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
449 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
450 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
451 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
452 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
453 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
454 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
455 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
456 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
457 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
458 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
459 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
460 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
461 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
462 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
463 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
464 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
465 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
466 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
467 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
468 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
469 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
470 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
471 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
472 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
473 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
474 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
475 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
476 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
477 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
478 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
479 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
480 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
481 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
482 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
483 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
484 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
485 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
486 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
487 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
488 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
489 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
490 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
491 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
492 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
493 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
494 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
495 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
496 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
497 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
498 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
499 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C
500 A = A + 1 : B = A * 2 + 1 : C = C + A / B : PRINT A, B, C

