#ifndef COMPILER_COMMAND_ID_H_INCLUDED
#define COMPILER_COMMAND_ID_H_INCLUDED

enum class CompilerCommandId {
  end_stmt,
  clear_stmt,
  def_stmt,
  cls_stmt,
  beep_stmt,
  print_stmt,
  input_stmt,
  goto_stmt,
  gosub_stmt,
  return_stmt,
  sound_stmt,
  out_stmt,
  poke_stmt,
  vpoke_stmt,
  ipoke_stmt,
  play_stmt,
  draw_stmt,
  let_stmt,
  if_stmt,
  for_stmt,
  next_stmt,
  dim_stmt,
  redim_stmt,
  randomize_stmt,
  locate_stmt,
  screen_stmt,
  width_stmt,
  color_stmt,
  pset_stmt,
  preset_stmt,
  line_stmt,
  paint_stmt,
  circle_stmt,
  copy_stmt,
  put_stmt,
  data_stmt,
  idata_stmt,
  read_stmt,
  iread_stmt,
  restore_stmt,
  irestore_stmt,
  resume_stmt,
  get_stmt,
  set_stmt,
  on_stmt,
  interval_stmt,
  key_stmt,
  strig_stmt,
  sprite_stmt,
  stop_stmt,
  wait_stmt,
  swap_stmt,
  call_stmt,
  cmd_stmt,
  maxfiles_stmt,
  open_stmt,
  open_grp_stmt,
  close_stmt,
  file_stmt,
  text_stmt,
  bload_stmt
};

#endif  // COMPILER_COMMAND_ID_H_INCLUDED
