10 CLS
20 PRINT "<<<< IF - COMPARE INTEGERS >>>>"
30 INPUT "VALUE A"; A%
40 INPUT "VALUE B"; B%
45 PRINT "A = "; A%; " B = "; B%
50 IF A% = 0 AND B% = 0 THEN END
60 IF A% = B% THEN PRINT "A IS EQUAL TO B"
70 IF A% > B% THEN PRINT "A IS GREATER THAN B" ELSE IF A% < B% THEN PRINT "A IS LESS THAN B"
80 BEEP : IF A% <> B% THEN BEEP : IF A% > B% THEN PRINT "A* <> B" : BEEP ELSE PRINT "A <> B*" : BEEP ELSE BEEP : PRINT "A* = B*"  
90 IF A% = 99 THEN 40 ELSE 30
100 IF A% = 100 GOTO 30 ELSE 40
110 IF A% = 20 GOTO 20 ELSE IF A% = 30 THEN 10 ELSE 30



