/***
 * @file cdb_export_strategy.cpp
 * @brief CDB (*.cdb) export strategy implementation
 * @author Amaury Carvalho (2019-2026)
 */

#include "cdb_export_strategy.h"

#include <cstdio>
#include <string>

#include "build_options.h"
#include "code_node.h"
#include "lexeme.h"
#include "symbol_manager.h"

using namespace std;

bool CdbExportStrategy::save(SymbolManager* symbolManager, BuildOptions* opts) {
  FILE* file;
  CodeNode* codeItem;
  int i, t, size;
  char s[512];

  auto& codeList = symbolManager->codeList;
  auto& dataList = symbolManager->dataList;

  symbolManager->exportFilename = opts->baseFilename + ".cdb";

  file = fopen(symbolManager->exportFilename.c_str(), "w");
  if (!file) return false;

  fprintf(file, "; CDB generated by msxbas2rom\n");
  fprintf(file, "; Compatible with openMSX sdcdb\n\n");

  // =====================================================
  // SOURCE FILE DECLARATION
  // =====================================================

  size = snprintf(s, sizeof(s), "F:G$%s$0$0({%s}$)\n\n",
                  opts->inputFilename.c_str(), opts->inputFilename.c_str());

  fwrite(s, 1, size, file);

  // =====================================================
  // CUSTOM TYPE DEFINITIONS
  // =====================================================

  // -----------------------------------------------------
  // FLOAT 24-bit
  // -----------------------------------------------------

  fprintf(file, "T:F24({3}ST)\n");
  fprintf(file, "F:F24:m0({1}SC:B),0,0\n");
  fprintf(file, "F:F24:m1({1}SC:B),1,0\n");
  fprintf(file, "F:F24:exp({1}SC:B),2,0\n\n");

  // -----------------------------------------------------
  // PASCAL STRING
  // -----------------------------------------------------

  fprintf(file, "T:PSTR({256}ST)\n");
  fprintf(file, "F:PSTR:len({1}SC:B),0,0\n");
  fprintf(file, "F:PSTR:data({255}DA255d,SC:B),1,0\n\n");

  // =====================================================
  // VARIABLES
  // =====================================================

  t = dataList.size();

  for (i = 0; i < t; i++) {
    codeItem = dataList[i];
    if (!codeItem || !codeItem->debug) continue;

    const string& name = codeItem->name;

    unsigned int addr = (codeItem->segm << 16) | codeItem->addr_within_segm;

    int totalSize = codeItem->length;

    string descriptor;
    string baseType;

    // -------------------------------------------------
    // Determine variable type
    // -------------------------------------------------

    if (codeItem->lexeme) {
      switch (codeItem->lexeme->subtype) {
          // INTEGER (16-bit signed)

        case Lexeme::subtype_numeric:
          baseType = "SI:B";
          break;

          // FLOAT 24-bit

        case Lexeme::subtype_single_decimal:
        case Lexeme::subtype_double_decimal:
          baseType = "F24";
          break;

          // PASCAL STRING

        case Lexeme::subtype_string:
        case Lexeme::subtype_basic_string:
          baseType = "PSTR";
          break;

        default:
          baseType = "SC:B";
          break;
      }

      // -------------------------------------------------
      // ARRAY dimensions
      // -------------------------------------------------

      if (codeItem->lexeme->isArray) {
        if (codeItem->lexeme->x_size) {
          descriptor += "DA";
          descriptor += to_string(codeItem->lexeme->x_size);
          descriptor += "d,";
        }

        if (codeItem->lexeme->y_size) {
          descriptor += "DA";
          descriptor += to_string(codeItem->lexeme->y_size);
          descriptor += "d,";
        }
      }

      descriptor += baseType;

    } else {
      descriptor = "SC:B";
    }

    // -------------------------------------------------
    // SYMBOL DEFINITION
    // -------------------------------------------------

    size = snprintf(s, sizeof(s), "S:G$%s$0_0$0({%d}%s),G,0,0\n", name.c_str(),
                    totalSize, descriptor.c_str());

    if (size <= 0) {
      fclose(file);
      return false;
    }

    fwrite(s, 1, size, file);

    // -------------------------------------------------
    // ADDRESS BINDING
    // -------------------------------------------------

    if (opts->megaROM) {
      size = snprintf(s, sizeof(s), "L:G$%s$0_0$0:%06X\n", name.c_str(), addr);

    } else {
      size = snprintf(s, sizeof(s), "L:G$%s$0_0$0:%04X\n", name.c_str(),
                      codeItem->addr_within_segm);
    }

    if (size <= 0) {
      fclose(file);
      return false;
    }

    fwrite(s, 1, size, file);
  }

  fprintf(file, "\n");

  // =====================================================
  // SOURCE LINE MAPPING (PHYSICAL LINES)
  // =====================================================

  t = codeList.size();

  for (i = 0; i < t; i++) {
    codeItem = codeList[i];
    if (!codeItem || !codeItem->debug) continue;

    unsigned int addr = (codeItem->segm << 16) | codeItem->addr_within_segm;

    string symbol = codeItem->name;

    // symbol definition

    size = snprintf(s, sizeof(s), "S:G$%s$0_0$0\n", symbol.c_str());

    fwrite(s, 1, size, file);

    // address binding

    if (opts->megaROM) {
      size =
          snprintf(s, sizeof(s), "L:G$%s$0_0$0:%06X\n", symbol.c_str(), addr);

    } else {
      size = snprintf(s, sizeof(s), "L:G$%s$0_0$0:%04X\n", symbol.c_str(),
                      codeItem->addr_within_segm);
    }

    fwrite(s, 1, size, file);

    // source line mapping

    size = snprintf(s, sizeof(s), "L:C$%s$%d$0$0\n",
                    opts->inputFilename.c_str(), codeItem->lineNumber);

    fwrite(s, 1, size, file);
  }

  fclose(file);

  return true;
}