name: Build all releases

on:
  workflow_dispatch:
    branches: [ master ]
    inputs:
      release:
        description: 'Release number'     
        required: true
        default: 'v0.0.0.0'
      publish_artifacts:
        description: 'Upload artifacts'
        required: true
        default: 'true'
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Make (clean, release)
      run: make clean release
    - if: github.event.inputs.publish_artifacts == 'true'
      name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: msxbas2rom_linux64_${{ github.event.inputs.release }}
        path: bin/Release/msxbas2rom

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Setup
      run: brew install argp-standalone
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Make -> clean release
      run: make clean release
    - if: github.event.inputs.publish_artifacts == 'true'
      name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: msxbas2rom_macos_${{ github.event.inputs.release }}
        path: bin/Release/msxbas2rom*

  build-windows64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          gcc
          git
          libargp-devel
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make -> clean release
      run: make clean release
    - if: github.event.inputs.publish_artifacts == 'true'
      name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: msxbas2rom_win64_${{ github.event.inputs.release }}
        path: bin/Release/msxbas2rom.exe

