name: Build all releases

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - uses: actions-ecosystem/action-release-label@v1
      id: release-label
      if: ${{ github.event.pull_request.merged == true }}
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      if: ${{ steps.release-label.outputs.level != null }}
      with:
        semver_only: true
    - name: Make (clean, release)
      run: make clean release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: msxbas2rom_linux64_${{ steps.get-latest-tag.outputs.tag }}
        path: bin/Release/msxbas2rom*.*

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Setup
      run: brew install argp-standalone
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - uses: actions-ecosystem/action-release-label@v1
      id: release-label
      if: ${{ github.event.pull_request.merged == true }}
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      if: ${{ steps.release-label.outputs.level != null }}
      with:
        semver_only: true
    - name: Check system
      run: find / -name *argp*
    - name: Make -> clean release
      run: make clean release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: msxbas2rom_macos_${{ steps.get-latest-tag.outputs.tag }}
        path: bin/Release/msxbas2rom*.*

  build-windows64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Setup
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          gcc
          git
          libargp-devel
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions-ecosystem/action-release-label@v1
      id: release-label
      if: ${{ github.event.pull_request.merged == true }}
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      if: ${{ steps.release-label.outputs.level != null }}
      with:
        semver_only: true
    - name: Make -> clean release
      run: make clean release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: msxbas2rom_win64_${{ steps.get-latest-tag.outputs.tag }}
        path: bin/Release/msxbas2rom*.*

