name: Build

on:
  workflow_call:

jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installing dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y devscripts build-essential \
            debhelper-compat=13 rpm rpmlint
      - name: Building Debian artifacts
        run: |
          make debian
      - name: Building RPM artifacts
        run: |
          make rpm
      - name: Preparing artifacts to upload
        run: |
          mkdir -p dist          
          mv bin/Release/msxbas2rom dist
      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: msxbas2rom-linux-x64-bin
          path: dist/*

  build-mac-x86_64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installing dependencies
        run: |
          brew install argp-standalone
      - name: Building artifacts
        run: |
          make clean release
      - name: Uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: msxbas2rom-mac-x86_64-bin
          path: bin/Release/msxbas2rom*

  build-windows-x32:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installing dependencies
        uses: egor-tensin/setup-mingw@v2.2.0
        with:
          platform: x86
          version: 12.2.0.3042023
      - name: Refreshing environment
        run: |
          refreshenv
          choco install make
      - name: Building artifacts (32 bits)
        run: |
          make PARMS=-m32 clean release
      - name: Uploading artifact (32bits)
        uses: actions/upload-artifact@v4
        with:
          name: msxbas2rom-windows-x32-bin
          path: bin/Release/msxbas2rom.exe

  build-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Installing dependencies
        uses: egor-tensin/setup-mingw@v2.2.0
        with:
          platform: x64
          version: 12.2.0.3042023
      - name: Building artifacts (32 bits)
        run: |
          make PARMS=-m64 clean release
      - name: Uploading artifact (64bits)
        uses: actions/upload-artifact@v4
        with:
          name: msxbas2rom-windows-x64-bin
          path: bin/Release/msxbas2rom.exe
