name: Build a new release

on:
  push:
    tags:
    - 'v*.*.*.*' # v0.0.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build all
      uses: amaurycarvalho/msxbas2rom/build_all.yml
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    - name: Packing linux artifact (x64)
      run: |
          tar cvzf  msxbas2rom-${{ github.ref }}-linux-x64-bin.tar.gz msxbas2rom-linux-x64-bin/*
    - name: Packing macos artifact (x86_64)
      run: |
          zip --junk-paths msxbas2rom-${{ github.ref }}-mac-x86_64-bin msxbas2rom-mac-x86_64-bin/*
    - name: Packing windows artifact (x32)
      run: |
          zip --junk-paths msxbas2rom-${{ github.ref }}-windows-x32-bin msxbas2rom-windows-x32-bin/*
    - name: Packing windows artifact (x64)
      run: |
          zip --junk-paths msxbas2rom-${{ github.ref }}-windows-x64-bin msxbas2rom-windows-x64-bin/*
    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body: |
            Changes in this release, run:
            msxbas2rom --ver
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload linux artifact (x64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: msxbas2rom-${{ github.ref }}-linux-x64-bin.tar.gz
        asset_name: msxbas2rom-${{ github.ref }}-linux-x64-bin.tar.gz
        asset_content_type: application/gzip
    - name: Upload macos artifact (x86_64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: msxbas2rom-${{ github.ref }}-mac-x86_64-bin.zip
        asset_name: msxbas2rom-${{ github.ref }}-mac-x86_64-bin.zip
        asset_content_type: application/gzip
    - name: Upload windows artifact (x32)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: msxbas2rom-${{ github.ref }}-windows-x32-bin.zip
        asset_name: msxbas2rom-${{ github.ref }}-windows-x32-bin.zip
        asset_content_type: application/gzip
    - name: Upload windows artifact (x64)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: msxbas2rom-${{ github.ref }}-windows-x64-bin.zip
        asset_name: msxbas2rom-${{ github.ref }}-windows-x64-bin.zip
        asset_content_type: application/gzip

