name: Test artifacts

on:
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Make (clean, release)
      run: make clean release
    - name: Do test
      run: |
        cp -av bin/Release/* test/check/simple
        cd test/check/simple
        chmod +x msxbas2rom
        array="$(ls *.bas)"
        for i in ${array[*]}; do
          echo $i
          ./msxbas2rom -c -q $i
        done
                   
  test-windows:
    runs-on: windows-latest
    steps:
    - name: Set up MinGW (64 bits)
      uses: Honeybunch/setup-mingw@v3
      with:
        platform: x64
    - name: Checkout
      uses: actions/checkout@v2
    - name: Make -> clean release (64bits)
      run: make PARMS=-m64 clean release
    - name: Do test
      run: |
          cp bin/Release/*.exe test/check/simple
          cd test/check/simple
          $files = Get-ChildItem -Path "." -Include *.bas
          foreach ($f in $files) {
            echo $f.FullName
            ./msxbas2rom -c -q $f.FullName
          }

