name: Test artifacts

on:
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
#    - name: Make (clean, release)
#      run: make clean release
    - name: Setup test
      id: finding-files
      run: |
        cp -av bin/Release/* test/check/simple
        cd test/check/simple
        chmod +x msxbas2rom
        echo "::set-output name=FILELIST::$(ls *.bas | jq -R -s -c 'split("\n")[:-1]')"
    - name: Do test
      run: |
        cd test/check/simple
        array=${{ fromJson(steps.finding-files.outputs.FILELIST) }}
        for i in ${array[*]} do
          for k in ${i[*]} do
            echo "$k"
          done
        done         
                   

