name: Test artifacts

on:
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
#    - name: Make (clean, release)
#      run: make clean release
    - name: Setup test
      id: finding-files
      run: |
        cp -av bin/Release/* test/check/simple
        cd test/check/simple
        chmod +x msxbas2rom
        echo "::set-output name=FILELIST::$(ls *.bas | jq -R -s -c 'split("\n")[:-1]')"
    - id: file-list
      uses: lucaspinheirogit/list-from-string-array-action@v1.4.3
      with:
        stringArray: ${{ steps.finding-files.outputs.FILELIST }}
    - name: Do test
      run: |
        cd test/check/simple
        for i in ${{ steps.file-list.outputs.stringList[@] }}; do
          ./msxbas2rom -c ${i}
        done         
                   

