name: Test artifacts

on:
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Make (clean, release)
      run: make clean release
    - name: Do test
      run: |
        cp -av bin/Release/* test/check/simple
        cd test/check/simple
        chmod +x msxbas2rom
        array="$(ls *.bas)"
        for i in ${array[*]}; do
          ./msxbas2rom -c $i
        done
                   

