name: Test artifacts

on:
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Make (clean, release)
      run: make clean release
    - name: Setup test
      id: finding-files
      run: |
        cp -av bin/Release/* test/check/simple
        cd test/check/simple
        chmod +x msxbas2rom
        echo "::set-output name=FILELIST::$(find . -name '*.bas' -print)"
    - name: Do test
      run: |
        cd test/check/simple
        IFS="," read -a myarray <<< ${{ steps.finding-files.outputs.FILELIST }}
        for i in "${myarray[@]}"; do
          file_path=$(dirname "${i}")
          file_name=$(basename "${i}")
          ./msxbas2rom -c file_name
        done           

