name: Test artifacts

on:
  workflow_dispatch:

jobs:
  build:
    name: Build all
    uses: ./.github/workflows/build_all.yml


  test-linux:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Download artifacts
      uses: actions/download-artifact@v3
    - name: Setup test
      id: finding-files
      run: |
        cp -av msxbas2rom-linux-x64-bin/* test/check/simple
        cd test/check/simple
        echo "::set-output name=FILELIST::$(find . -name '*.bas' -print)"
    - name: Do test
      run: |
        IFS="," read -a myarray <<< ${{ steps.finding-files.outputs.FILELIST }}
        for i in "${myarray[@]}"; do
          file_path=$(dirname "${i}")
          file_name=$(basename "${i}")
          msxbas2rom -c file_name
        done           

  test-mac:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Download artifacts
      uses: actions/download-artifact@v3

  test-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v3

